- pages/index.tsx
- pages/student/classroom/[classroomName].tsx
- pages/teacher/classroom/[classroomName].tsx
Closes #22 
- feat: Added list of active students to teachers page
- feat: Teacher is notified whenever a new student enters
- refactor: replaces adding or deleting classroom from RESTful commands to socket events
Test plan: 
- Ran backend branch: https://github.com/mssiegel/frempco-server/pull/4
- I activated the classroom, then opened a separate browser tab and joined as a student. The student appeared on the teachers page. I then closed my teacher browser tab.  I could no longer access the classroom as a student.
> Teacher notified when student enters classroom

- pages/student/classroom/[classroomName].tsx
- src/components/pages/StudentsPage/Chatbox.css.tsx
- src/components/pages/StudentsPage/Chatbox.tsx
- src/components/pages/StudentsPage/Conversation.css.tsx
- src/components/pages/StudentsPage/Conversation.tsx
- src/components/pages/StudentsPage/SendMessages.css.tsx
- src/components/pages/StudentsPage/SendMessages.tsx
> Added static chatbox design to student's page

- package-lock.json
- package.json
- src/components/pages/StudentsPage/Conversation.tsx
Closes #32
- Added npm `bad-words` to cleanup bad words in chat messages
> Filters out bad words

- src/components/pages/TeachersPage/index.tsx
This PR Closes #40 
Set Teacher Chat Display to first pair of students
> Closes Issue #40 default chat display

- src/components/pages/StudentsPage/SendMessages.css.tsx
- src/components/pages/StudentsPage/SendMessages.tsx
- src/components/pages/TeachersPage/UnpairedStudentsList.tsx
- src/components/pages/TeachersPage/index.tsx
This PR closes #36 
and adds Peer Left Chat Notifications and handling.
This PR will be accompanied by back end changes as well. Will update here when that PR is in.
> Add Feature Peer Left Chat Notification

- src/components/pages/StudentsPage/Conversation.css.tsx
- src/components/pages/StudentsPage/Conversation.tsx
- src/components/pages/StudentsPage/SendMessages.css.tsx
- src/components/pages/StudentsPage/SendMessages.tsx
- src/components/pages/TeachersPage/Conversation.css.tsx
- src/components/pages/TeachersPage/Conversation.tsx
Adds Feature: Peer is Typing Notification
Closes #35 
This PR is accompanied by a backend Server PR: https://github.com/mssiegel/frempco-server/pull/6
> Adds Feature Peer is Typing Notification

- pages/index.tsx
- src/components/pages/StudentsPage/Chatbox.tsx
- src/components/pages/StudentsPage/SendMessages.css.tsx
- src/components/pages/StudentsPage/SendMessages.tsx
- src/components/shared/Modal.tsx
- src/components/shared/ModalTextField.tsx
- src/utils/classrooms.tsx
Minor refactors and edits of latests PRs.  The main refactor is for the modals on the homepage.   
Corresponding backend PR for refactor of peer is typing: https://github.com/mssiegel/frempco-server/pull/8
This covers all the latest PRs except the peer left notification PR. I will cover that in a separate PR. 
**Test plan:** I tested by logging in as a teacher and then pairing up two test students. The app worked as expected.
> Refactors of latest pull requests

- pages/_app.tsx
- pages/index.tsx
- src/components/pages/StudentsPage/index.tsx
- src/components/pages/TeachersPage/ActivateButton.tsx
- src/components/pages/TeachersPage/index.tsx
- src/contexts/UserContext.tsx
Closes Issue #53
Related Backend PR: https://github.com/mssiegel/frempco-server/pull/10
I've made these changes (including the backend PR) live on my temp server: [http://208.87.134.100:3000](http://208.87.134.100:3000)
> Closes Issue #53

- src/components/pages/TeachersPage/UnpairedStudentsList.tsx
- src/utils/classrooms.tsx
This PR/Branch is a demo of a feature to add an editable character list to the teachers page.
This will allow the teacher to create their own character lists that will still randomly be assigned as usual.
Additionally, logic has been provided for if the teacher empties the list, the character name will default to the users real name.
> Proposed Feature Edit Character List

- src/components/shared/Layout.tsx
> Fixes #67 Nested Header Logs in Development

- src/components/pages/TeachersPage/PairedStudentsList.tsx
- src/components/pages/TeachersPage/index.tsx
Closes #60 Allow Teacher to Unpair Students
Related Backend PR https://github.com/mssiegel/frempco-server/pull/12
This PR allows the teacher to unpair students from their dashboard using an unpair button as shown in the image below.
> Closes #60 Allow Teacher to Unpair Students

- src/components/pages/TeachersPage/PairedStudentsList.css.tsx
- src/components/pages/TeachersPage/PairedStudentsList.tsx
- src/components/pages/TeachersPage/index.tsx
Closes #52 Highlight Selected Student Pair
This PR adds highlighting to the selected student pair in the teachers dashboard as shown in the image below.
> Closes #52 Highlight Selected Student Pair

- data/classrooms.json
resolves #77 
Clicking the dev mode shortcuts will use classroom "test":
Teacher page:
Student page:
> added test classroom

- pages/index.tsx
resolves #79 
Using the development shortcut link the student is put in the test classroom with an auto generated name:
> Fixes #79 Dev link shortcut not adding student to classroom

- pages/index.tsx
Great work merging PR #84. I'm glad you did it without waiting for me as that lets us move faster!
I made this PR to put repetitive code from `visitStudentsPage()` and `testVisitStudentsPage()` into its own helper function. 
**Test plan:** I clicked the regular Student login button and the dev link and both took me to student's page.
> Refactors code from visiting student dev page to use a helper function

- src/components/pages/StudentsPage/index.tsx
- src/components/pages/TeachersPage/UnpairedStudentItem.tsx
- src/components/pages/TeachersPage/UnpairedStudentsList.tsx
Closes #54 Ability to Remove Student From Classroom
Related Backend PR https://github.com/mssiegel/frempco-server/pull/11
> Closes #54 Ability to Remove Student From Classroom

- README.md
I created a dev site [dev.frempco.com](https://dev.frempco.com/) on Vercel. It is connected to our `dev` branch.  This PR will be our first one merged into our `dev` branch!
> Added dev site to our readme

- .env.development
I feel we sometimes might need to debug the prod and development servers. Having their urls in the .env will make it easy to find them.
> Updated .env with the correct dev and prod urls

- .env.development
- README.md
Merging so that the latest code appears in main
> Merging `dev` to `main`

- src/components/pages/StudentsPage/WelcomeMessage.css.tsx
- src/components/pages/StudentsPage/WelcomeMessage.tsx
- src/components/pages/StudentsPage/index.tsx
Closes #97 
Added a box to include the welcome message when a student joins a classroom:
When student gets removed:
> Better welcome message

- src/components/pages/HomePage/DevLinkShortcuts.tsx
- src/components/pages/HomePage/index.tsx
Fixes #105 
Added debounce to our onClick function, so it is only called once when spam clicked.
**Test Plan:** Tried a few variations of spam clicking and double clicking, the dev student link.
> added throttle to dev student link

- src/components/pages/TeachersPage/UnpairedStudentsList.tsx
Resolves #116 
Added "Pair up" button, color for every other row, and modified text in "Pair up all students" button.
**Test plan:** Did a few test runs with 6 students, lots of pairing, unpairing, and shuffling, so far works for me.
> Improve teachers flexibility when matching up students for #116

- src/components/pages/StudentsPage/Chatbox.css.tsx
Fixes #120 
Changed the chatbox width to 100% or 500px for desktop
Mobile view:
Desktop:
> iss-120 fixed chatbox width

- src/components/pages/HomePage/DevLinkShortcuts.tsx
- src/components/pages/HomePage/StudentsButton.tsx
- src/components/pages/HomePage/TeachersButton.tsx
- src/components/pages/HomePage/index.tsx
- src/components/shared/Modal.tsx
This is just a refactor. It moves the Homepage's visit teachers page button to its own component.
**Test plan:** I went on localhost and everything correctly looked the same. I was able to enter as a teacher.
> Refactor: Homepage's teachers button

- src/components/pages/HomePage/ExampleChat.tsx
- src/components/pages/HomePage/index.tsx
Refactored the Homepage's example chat into its own component
**Test plan:** the homepage looked the same on my localhost
> Refactor: Homepage example chat

- src/components/pages/TeachersPage/SetCharacterList.tsx
- src/components/pages/TeachersPage/UnpairedStudentsList.tsx
Refactored set character list button into its own component.
**Test plan:** on localhost I updated the set character list and paired up students. It worked as expected.
> Refactor: set character list button
